language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
 - chmod +x ./gradlew

script:
 - ./gradlew build

sudo: false